### ISSUE TITLE
IE 8, IE 9: <picture> not working

### ISSUE THREAD

**Issue by wlanni** [Abban/jQuery-Picture#12]
Hey there,

Getting broken images in IE8, IE9, using picture element.
img src is coming back 'undefined'

Tried in jQuery version 1.8.3, as well as 1.9.1 with the migrate plugin.

figure works fine in both browser versions.

Crap. And I'm on a private production / dev server on a site that is undergoing client review, so I need to revert back and not use this code. Can't share out a sample. !(*$!

**Comment by Abban** [comment]
Howdy,

Try swapping your HTML picture tags for figure ones. I reckon the issue is
that the picture tag isn't valid HTML yet. Also are you using modernizr?

Ab.

On Wednesday, February 13, 2013, Will Lanni wrote:

> Looks like IE is not finding the 'source' in getCurrentMedia:
> element.find('source').each(function()... (line 88) -- seems like 'source'
> isn't appearing as part of the object, whereas in other browsers it is.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Abban/jQuery-Picture/issues/12#issuecomment-13510477.

## 

_Abban Dunne_

## Web De/sign/velop/er

_E:_ himself@abandon.ie*
*_M:_ 0834237525
www.abandon.ie http://abandon.ie

## @abbandunne http://twitter.com/abbandunne

Smooth Social http://smoothsocial.com, coming soon. Register your
interest, get access before anyone else and rub it in their jealous faces.

**Comment by wlanni** [comment]
hmm... looks like it could be the setPicture. ie9 doesn't seem to be looping through the element.find('source').each() function. var path isn't getting set; the sizes object isn't getting any values set.

**Comment by wlanni** [comment]
Oops should have refreshed before I posted. Yep, good call, you're right that picture isn't valid html. And yeah, I'm using modernizr, but didn't even think to look at the html classes.--though I just did and picture isn't coming up in it. Anyway, I'll switch over to figure html elements and be done with it.

**Comment by fcalderan** [comment]
I had the same issue with IE9 and after googling a while I came to this helpful page: http://www.w3.org/community/respimg/2012/03/06/js-implementation-problem-with/
